version: '3'
services:
  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./data/html:/var/www/html
  app:
    build: ./app
    volumes:
      - ./data/html:/var/www/html
