version: '3'
services:
  web:
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./data/html:/var/www/html
  app:
    build: ./app
    env_file: .env
    environment:
      DATABASE_HOST: mysql
    depends_on:
      - mysql
    volumes:
      - ./data/html:/var/www/html
  mysql:
    build: ./mysql
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/initial.sql:/docker-entrypoint-initdb.d/initial.sql

volumes:
  db-data:
