version: '3'
services:
  web:
    image: nginx:1.15.5-alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/html:/var/www/html
  app:
    build: ./app
    volumes:
      - ./data/html:/var/www/html
